const data = [
    {
        title: "Friedrich Nietzsche",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Nietzsche187a.jpg/800px-Nietzsche187a.jpg",
        description: "Friedrich Wilhelm Nietzsche (/ˈniːtʃə, ˈniːtʃi/;[22][23] German: [ˈfʁiːdʁɪç ˈvɪlhɛlm ˈniːtʃə] (About this soundlisten) or [ˈniːtsʃə];[24][25] 15 October 1844 – 25 August 1900) was a German philosopher, cultural critic, composer, poet, and philologist whose work has exerted a profound influence on modern intellectual history.[26][27][28][29][30] He began his career as a classical philologist before turning to philosophy. He became the youngest person ever to hold the Chair of Classical Philology at the University of Basel in 1869 at the age of 24.[31] Nietzsche resigned in 1879 due to health problems that plagued him most of his life; he completed much of his core writing in the following decade.[32] In 1889, at age 44, he suffered a collapse and afterward a complete loss of his mental faculties.[33] He lived his remaining years in the care of his mother until her death in 1897 and then with his sister Elisabeth Förster-Nietzsche. Nietzsche died in 1900.[34]\n" +
            "\n" +
            "Nietzsche's writing spans philosophical polemics, poetry, cultural criticism, and fiction while displaying a fondness for aphorism and irony.[35] Prominent elements of his philosophy include his radical critique of truth in favor of perspectivism; genealogical critique of religion and Christian morality and related theory of master–slave morality;[27][36][i] aesthetic affirmation of existence in response to the \"death of God\" and the profound crisis of nihilism;[27] notion of the Apollonian and Dionysian; and characterization of the human subject as the expression of competing wills, collectively understood as the will to power.[37] He also developed influential concepts such as the Übermensch and the doctrine of eternal return.[38][39] In his later work, he became increasingly preoccupied with the creative powers of the individual to overcome social, cultural and moral contexts in pursuit of new values and aesthetic health.[30] His body of work touched a wide range of topics, including art, philology, history, religion, tragedy, culture, and science, and drew early inspiration from figures such as philosopher Arthur Schopenhauer,[15] composer Richard Wagner,[15] and writer Johann Wolfgang von Goethe.[15]\n" +
            "\n" +
            "After his death, his sister Elisabeth became the curator and editor of Nietzsche's manuscripts. She edited his unpublished writings to fit her German nationalist ideology while often contradicting or obfuscating Nietzsche's stated opinions, which were explicitly opposed to antisemitism and nationalism. Through her published editions, Nietzsche's work became associated with fascism and Nazism;[40] 20th-century scholars contested this interpretation and corrected editions of his writings were soon made available. Nietzsche's thought enjoyed renewed popularity in the 1960s and his ideas have since had a profound impact on 20th and early-21st century thinkers across philosophy—especially in schools of continental philosophy such as existentialism, postmodernism and post-structuralism—as well as art, literature, psychology, politics, and popular culture.",
        works: [
            {
                image: "https://images-na.ssl-images-amazon.com/images/I/51YSf4h9tEL._AC_UL600_SR399,600_.jpg",
                title: 'Beyond Good and Evil',
                description: "Beyond Good and Evil: Prelude to a Philosophy of the Future (German: Jenseits von Gut und Böse: Vorspiel einer Philosophie der Zukunft) is a book by philosopher Friedrich Nietzsche that expands the ideas of his previous work Thus Spoke Zarathustra with a more critical and polemical approach. It was first published in 1886.\n" +
                    "\n" +
                    "In Beyond Good and Evil, Nietzsche accuses past philosophers of lacking critical sense and blindly accepting dogmatic premises in their consideration of morality. Specifically, he accuses them of founding grand metaphysical systems upon the faith that the good man is the opposite of the evil man, rather than just a different expression of the same basic impulses that find more direct expression in the evil man. The work moves into the realm \"beyond good and evil\" in the sense of leaving behind the traditional morality which Nietzsche subjects to a destructive critique in favour of what he regards as an affirmative approach that fearlessly confronts the perspectival nature of knowledge and the perilous condition of the modern individual."
            },
            {
                image: "https://images-na.ssl-images-amazon.com/images/I/4177g1L0NOL._SX322_BO1,204,203,200_.jpg",
                title: 'Thus Spoke Zarathustra\n',
                description: "Thus Spoke Zarathustra, the ideas of which first came to Nietzsche while walking on two roads surrounding Rapallo, was conceived while writing The Gay Science.[ii] More specifically, the concept of the eternal recurrence, which is the central idea of Zarathustra by Nietzsche's admission, first occurred to Nietzsche in Switzerland: he was inspired by the sight of a gigantic, towering, pyramidal rock—a \"pyramidal block of stone\"—while walking through the woods along the shores of Lake Silvaplana, in the Upper Engadine, a high alpine region whose valley floor is at 6,000 feet (1,800 m). As evidence of this, he made a small note that read \"6,000 feet beyond man and time.\"[2]\n" +
                    "\n" +
                    "Nietzsche planned to write the book in three parts over several years. Although Part Three was originally planned to be the end of the book, ending with a strong climax, Nietzsche subsequently decided to write an additional three parts; ultimately, however, he composed only the fourth part, which is viewed to constitute an intermezzo. Nietzsche commented in Ecce Homo that for the completion of each part, \"[t]en days sufficed; in no case, neither for the first nor for the third and last, did I require more.\"[3]\n" +
                    "\n" +
                    "The first three parts were first published separately, and were subsequently published in a single volume in 1887. The fourth part remained private after Nietzsche wrote it in 1885; a scant forty copies were all that were printed, apart from seven others that were distributed to Nietzsche's close friends. In March 1892, the four parts were finally reprinted as a single volume. Since then, the version most commonly produced has included all four parts.\n" +
                    "\n" +
                    "The original text contains a great deal of word-play. For instance, words beginning with über ('over, above') and unter ('down, below') are often paired to emphasise the contrast, which is not always possible to bring out in translation, except by coinages. An example is untergang (lit. 'down-going'), which is used in German to mean 'setting' (as in, of the sun), but also 'sinking', 'demise', 'downfall', or 'doom'. Nietzsche pairs this word with its opposite übergang ('over-going'), used to mean 'transition'. Another example is übermensch ('overman' or 'superman'), discussed later in this article."
            },
            {
                image: "https://images-na.ssl-images-amazon.com/images/I/71oI1qfrUPL.jpg",
                title: 'On the Genealogy of Morality',
                description: "Nietzsche's treatise outlines his thoughts \"on the origin of our moral prejudices\" previously given brief expression in his Human, All Too Human (1878). Nietzsche attributes the desire to publish his \"hypotheses\" on the origins of morality to reading his friend Paul Rée's book The Origin of the Moral Sensations (1877) and finding the \"genealogical hypotheses\" offered there unsatisfactory.\n" +
                    "\n" +
                    "Nietzsche decided that \"a critique of moral values\" was needed, that \"the value of these values themselves must be called into question\". To this end Nietzsche provides a history of morality, rather than a hypothetical account in the style of Rée, whom Nietzsche classifies as an \"English psychologist\"[2] (using \"English\" to designate an intellectual temperament, as distinct from a nationality)."
            },
            {
                image: "https://img1.od-cdn.com/ImageType-400/6251-1/186/118/78/%7B18611878-BCA7-49D0-A13A-36E4CCFA5A55%7DImg400.jpg",
                title: 'The Gay Science',
                description: "The Gay Science (German: Die fröhliche Wissenschaft) or occasionally translated as The Joyful Wisdom is a book by Friedrich Nietzsche, first published in 1882 and followed by a second edition, which was published after the completion of Thus Spoke Zarathustra and Beyond Good and Evil, in 1887. This substantial expansion includes a fifth book and an appendix of songs. It was noted by Nietzsche to be \"the most personal of all [his] books\", and contains the greatest number of poems in any of his published works."
            },
        ],
    }, {
        title: "Fyodor Dostoevsky",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Vasily_Perov_-_%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%A4.%D0%9C.%D0%94%D0%BE%D1%81%D1%82%D0%BE%D0%B5%D0%B2%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_-_Google_Art_Project.jpg/800px-Vasily_Perov_-_%D0%9F%D0%BE%D1%80%D1%82%D1%80%D0%B5%D1%82_%D0%A4.%D0%9C.%D0%94%D0%BE%D1%81%D1%82%D0%BE%D0%B5%D0%B2%D1%81%D0%BA%D0%BE%D0%B3%D0%BE_-_Google_Art_Project.jpg",
        description: "Fyodor Mikhailovich Dostoevsky[a] (/ˌdɒstəˈjɛfski, ˌdʌs-/;[1] Russian: Фёдор Михайлович Достоевский[b], tr. Fyódor Mikháylovich Dostoyévskiy, IPA: [ˈfʲɵdər mʲɪˈxajləvʲɪdʑ dəstɐˈjɛfskʲɪj] (About this soundlisten); 11 November 1821 – 9 February 1881[2][c]), sometimes transliterated Dostoyevsky, was a Russian novelist, philosopher, short story writer, essayist, and journalist. Dostoevsky's literary works explore human psychology in the troubled political, social, and spiritual atmospheres of 19th-century Russia, and engage with a variety of philosophical and religious themes. His most acclaimed works include Crime and Punishment (1866), The Idiot (1869), Demons (1872), and The Brothers Karamazov (1880). Dostoevsky's body of works consists of 12 novels, four novellas, 16 short stories, and numerous other works. Many literary critics rate him as one of the greatest psychological novelists in world literature.[3] His 1864 novel Notes from Underground is considered to be one of the first works of existentialist literature.\n" +
            "\n" +
            "Born in Moscow in 1821, Dostoevsky was introduced to literature at an early age through fairy tales and legends, and through books by Russian and foreign authors. His mother died in 1837 when he was 15, and around the same time, he left school to enter the Nikolayev Military Engineering Institute. After graduating, he worked as an engineer and briefly enjoyed a lavish lifestyle, translating books to earn extra money. In the mid-1840s he wrote his first novel, Poor Folk, which gained him entry into St. Petersburg's literary circles. Arrested in 1849 for belonging to a literary group that discussed banned books critical of Tsarist Russia, he was sentenced to death but the sentence was commuted at the last moment. He spent four years in a Siberian prison camp, followed by six years of compulsory military service in exile. In the following years, Dostoevsky worked as a journalist, publishing and editing several magazines of his own and later A Writer's Diary, a collection of his writings. He began to travel around western Europe and developed a gambling addiction, which led to financial hardship. For a time, he had to beg for money, but he eventually became one of the most widely read and highly regarded Russian writers.\n" +
            "\n" +
            "Dostoevsky was influenced by a wide variety of philosophers and authors including Pushkin, Gogol, Augustine, Shakespeare, Dickens, Balzac, Lermontov, Hugo, Poe, Plato, Cervantes, Herzen, Kant, Belinsky, Hegel, Schiller, Solovyov, Bakunin, Sand, Hoffmann, and Mickiewicz.\n" +
            "\n" +
            "His writings were widely read both within and beyond his native Russia and influenced an equally great number of later writers including Russians like Aleksandr Solzhenitsyn and Anton Chekhov, philosophers Friedrich Nietzsche and Jean-Paul Sartre and the emergence of Existentialism and Freudianism.[4] His books have been translated into more than 170 languages.",
        works: [
            {
                image: "https://m.media-amazon.com/images/I/41AM6pjaZhL.jpg",
                title: "Crime and Punishment",
                description: "Crime and Punishment (pre-reform Russian: Преступленіе и наказаніе; post-reform Russian: Преступление и наказание, tr. Prestupléniye i nakazániye, IPA: [prʲɪstʊˈplʲenʲɪje ɪ nəkɐˈzanʲɪje]) is a novel by the Russian author Fyodor Dostoevsky. It was first published in the literary journal The Russian Messenger in twelve monthly installments during 1866.[1] It was later published in a single volume. It is the second of Dostoevsky's full-length novels following his return from ten years of exile in Siberia. Crime and Punishment is considered the first great novel of his \"mature\" period of writing.[2] The novel is often cited as one of the supreme achievements in literature.[3][4][5][6]\n" +
                    "\n" +
                    "Crime and Punishment focuses on the mental anguish and moral dilemmas of Rodion Raskolnikov, an impoverished ex-student in Saint Petersburg who formulates a plan to kill an unscrupulous pawnbroker for her money. Before the killing, Raskolnikov believes that with the money he could liberate himself from poverty and go on to perform great deeds. However, once it is done he finds himself racked with confusion, paranoia, and disgust for what he has done. His justifications disintegrate completely as he struggles with guilt and horror and confronts the real-world consequences of his deed."
            },
            {
                image: "https://m.media-amazon.com/images/I/51Bz-aHxQXL.jpg",
                title: "The Brothers Karamazov",
                description: "The Brothers Karamazov (Russian: Бра́тья Карама́зовы, Brat'ya Karamazovy, pronounced [ˈbratʲjə kərɐˈmazəvɨ]), also translated as The Karamazov Brothers, is the final novel by Russian author Fyodor Dostoevsky. Dostoevsky spent nearly two years writing The Brothers Karamazov, which was published as a serial in The Russian Messenger from January 1879 to November 1880. Dostoevsky died less than four months after its publication.\n" +
                    "\n" +
                    "Set in 19th-century Russia, The Brothers Karamazov is a passionate philosophical novel that enters deeply into questions of God, free will, and morality. It is a theological drama dealing with problems of faith, doubt and reason in the context of a modernizing Russia, with a plot that revolves around the subject of patricide. Dostoevsky composed much of the novel in Staraya Russa, which inspired the main setting.[1] Since its publication, it has been acclaimed as one of the supreme achievements in world literature.[2]"
            },
            {
                image: "https://images-na.ssl-images-amazon.com/images/I/41m4pPorKPL.jpg",
                title: "The Idiot",
                description: "The Idiot (pre-reform Russian: Идіотъ; post-reform Russian: Идиот, tr. Idiót) is a novel by the 19th-century Russian author Fyodor Dostoevsky. It was first published serially in the journal The Russian Messenger in 1868–69.\n" +
                    "\n" +
                    "The title is an ironic reference to the central character of the novel, Prince (Knyaz) Lev Nikolayevich Myshkin, a young man whose goodness, open-hearted simplicity and guilelessness lead many of the more worldly characters he encounters to mistakenly assume that he lacks intelligence and insight. In the character of Prince Myshkin, Dostoevsky set himself the task of depicting \"the positively good and beautiful man.\"[1] The novel examines the consequences of placing such a unique individual at the centre of the conflicts, desires, passions and egoism of worldly society, both for the man himself and for those with whom he becomes involved.\n" +
                    "\n" +
                    "Joseph Frank describes The Idiot as \"the most personal of all Dostoevsky's major works, the book in which he embodies his most intimate, cherished, and sacred convictions.\"[2] It includes descriptions of some of his most intense personal ordeals, such as epilepsy and mock execution, and explores moral, spiritual and philosophical themes consequent upon them. His primary motivation in writing the novel was to subject his own highest ideal, that of true Christian love, to the crucible of contemporary Russian society.\n" +
                    "\n" +
                    "The artistic method of conscientiously testing his central idea meant that the author could not always predict where the plot was going as he was writing. The novel has an awkward structure, and many critics have commented on its seemingly chaotic organization. According to Gary Saul Morson, \"The Idiot violates every critical norm and yet somehow manages to achieve real greatness.\"[3] Dostoevsky himself was of the opinion that the experiment was not entirely successful, but the novel remained his favourite among his works. In a letter to Strakhov he wrote: \"Much in the novel was written hurriedly, much is too diffuse and did not turn out well, but some of it did turn out well. I do not stand behind the novel, but I do stand behind the idea.\"[4]"
            },
            {
                image: "https://upload.wikimedia.org/wikipedia/commons/b/b3/Notes_from_underground_cover.jpg",
                title: "Notes from Underground",
                description: "Notes from Underground (pre-reform Russian: Записки изъ подполья; post-reform Russian: Записки из подполья, Zapíski iz podpólʹya; also translated as Notes from the Underground or Letters from the Underworld) is an 1864 novel by Fyodor Dostoevsky, and is considered by many to be one of the first existentialist novels.[1]\n" +
                    "\n" +
                    "It presents itself as an excerpt from the rambling memoirs of a bitter, isolated, unnamed narrator (generally referred to by critics as the Underground Man), who is a retired civil servant living in St. Petersburg. The first part of the story is told in monologue form through the Underground Man's diary, and attacks contemporary Russian philosophy, especially Nikolay Chernyshevsky's What Is to Be Done?.[2] The second part of the book is called \"Apropos of the Wet Snow\" and describes certain events that appear to be destroying and sometimes renewing the underground man, who acts as a first person, unreliable narrator and anti-hero.[3]"
            },

        ],
    }, {
        title: "Charles Dickens",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Dickens_Gurney_head.jpg/300px-Dickens_Gurney_head.jpg",
        description: "Charles John Huffam Dickens FRSA (/ˈdɪkɪnz/; 7 February 1812 – 9 June 1870) was an English writer and social critic. He created some of the world's best-known fictional characters and is regarded by many as the greatest novelist of the Victorian era.[1] His works enjoyed unprecedented popularity during his lifetime, and by the 20th century, critics and scholars had recognised him as a literary genius. His novels and short stories are still widely read today.[2][3]\n" +
            "\n" +
            "Born in Portsmouth, Dickens left school to work in a factory when his father was incarcerated in a debtors' prison. Despite his lack of formal education, he edited a weekly journal for 20 years, wrote 15 novels, five novellas, hundreds of short stories and non-fiction articles, lectured and performed readings extensively, was an indefatigable letter writer, and campaigned vigorously for children's rights, education, and other social reforms.\n" +
            "\n" +
            "Dickens's literary success began with the 1836 serial publication of The Pickwick Papers. Within a few years he had become an international literary celebrity, famous for his humour, satire, and keen observation of character and society. His novels, most published in monthly or weekly instalments, pioneered the serial publication of narrative fiction, which became the dominant Victorian mode for novel publication.[4][5] Cliffhanger endings in his serial publications kept readers in suspense.[6] The installment format allowed Dickens to evaluate his audience's reaction, and he often modified his plot and character development based on such feedback.[5] For example, when his wife's chiropodist expressed distress at the way Miss Mowcher in David Copperfield seemed to reflect her disabilities, Dickens improved the character with positive features.[7] His plots were carefully constructed, and he often wove elements from topical events into his narratives.[8] Masses of the illiterate poor chipped in ha'pennies to have each new monthly episode read to them, opening up and inspiring a new class of readers.[9]\n" +
            "\n" +
            "His 1843 novella A Christmas Carol remains especially popular and continues to inspire adaptations in every artistic genre. Oliver Twist and Great Expectations are also frequently adapted and, like many of his novels, evoke images of early Victorian London. His 1859 novel A Tale of Two Cities (set in London and Paris) is his best-known work of historical fiction. The most famous celebrity of his era, he undertook, in response to public demand, a series of public reading tours in the later part of his career.[10] Dickens has been praised by many of his fellow writers – from Leo Tolstoy to George Orwell, G. K. Chesterton, and Tom Wolfe – for his realism, comedy, prose style, unique characterisations, and social criticism. However, Oscar Wilde, Henry James, and Virginia Woolf complained of a lack of psychological depth, loose writing, and a vein of sentimentalism.",
        works: [
            {
                image: "https://www.sonypictures.com/sites/default/files/styles/max_560x840/public/chameleon/title-movie/252681_oliver_twist_2005_1400x2100_2.jpg?itok=YyXmXEL5",
                title: "Oliver Twist",
                description: "Oliver Twist; or, the Parish Boy's Progress is Charles Dickens's second novel, and was published as a serial from 1837 to 1839 and released as a three-volume book in 1838, before the serialization ended.[1] The story centres on orphan Oliver Twist, born in a workhouse and sold into apprenticeship with an undertaker. After escaping, Oliver travels to London, where he meets the \"Artful Dodger\", a member of a gang of juvenile pickpockets led by the elderly criminal Fagin.\n" +
                    "\n" +
                    "Oliver Twist is notable for its unromantic portrayal of criminals and their sordid lives, as well as for exposing the cruel treatment of the many orphans in London in the mid-19th century.[2] The alternative title, The Parish Boy's Progress, alludes to Bunyan's The Pilgrim's Progress, as well as the 18th-century caricature series by William Hogarth, A Rake's Progress and A Harlot's Progress.[3]\n" +
                    "\n" +
                    "In this early example of the social novel, Dickens satirises the hypocrisies of his time, including child labour, the recruitment of children as criminals, and the presence of street children. The novel may have been inspired by the story of Robert Blincoe, an orphan whose account of working as a child labourer in a cotton mill was widely read in the 1830s. It is likely that Dickens's own experiences as a youth contributed as well.[4]\n" +
                    "\n" +
                    "Oliver Twist has been the subject of numerous adaptations for various media, including a highly successful musical play, Oliver!, and the multiple Academy Award-winning 1968 motion picture. Disney also put its spin on the novel with the animated film called Oliver & Company in 1988.[5]"
            },
            {
                image: "https://m.media-amazon.com/images/I/516Ol9454xL.jpg",
                title: "A Christmas Carol",
                description: "A Christmas Carol. In Prose. Being a Ghost Story of Christmas, commonly known as A Christmas Carol, is a novella by Charles Dickens, first published in London by Chapman & Hall in 1843 and illustrated by John Leech. A Christmas Carol recounts the story of Ebenezer Scrooge, an elderly miser who is visited by the ghost of his former business partner Jacob Marley and the spirits of Christmas Past, Present and Yet to Come. After their visits, Scrooge is transformed into a kinder, gentler man.\n" +
                    "\n" +
                    "Dickens wrote A Christmas Carol during a period when the British were exploring and re-evaluating past Christmas traditions, including carols, and newer customs such as Christmas trees. He was influenced by the experiences of his own youth and by the Christmas stories of other authors, including Washington Irving and Douglas Jerrold. Dickens had written three Christmas stories prior to the novella, and was inspired following a visit to the Field Lane Ragged School, one of several establishments for London's street children. The treatment of the poor and the ability of a selfish man to redeem himself by transforming into a more sympathetic character are the key themes of the story. There is discussion among academics as to whether this is a fully secular story, or if it is a Christian allegory.\n" +
                    "\n" +
                    "Published on 19 December, the first edition sold out by Christmas Eve; by the end of 1844 thirteen editions had been released. Most critics reviewed the novella favourably. The story was illicitly copied in January 1844; Dickens took legal action against the publishers, who went bankrupt, further reducing Dickens's small profits from the publication. He went on to write four other Christmas stories in subsequent years. In 1849 he began public readings of the story, which proved so successful he undertook 127 further performances until 1870, the year of his death. A Christmas Carol has never been out of print and has been translated into several languages; the story has been adapted many times for film, stage, opera and other media.\n" +
                    "\n" +
                    "A Christmas Carol captured the zeitgeist of the mid-Victorian revival of the Christmas holiday. Dickens had acknowledged the influence of the modern Western observance of Christmas and later inspired several aspects of Christmas, including family gatherings, seasonal food and drink, dancing, games and a festive generosity of spirit."
            },
            {
                image: "https://m.media-amazon.com/images/I/51HbH+Fn68L.jpg",
                title: "Great Expectations",
                description: "Great Expectations is the thirteenth novel by Charles Dickens and his penultimate completed novel, which depicts the education of an orphan nicknamed Pip (the book is a bildungsroman, a coming-of-age story). It is Dickens's second novel, after David Copperfield, to be fully narrated in the first person.[N 1] The novel was first published as a serial in Dickens's weekly periodical All the Year Round, from 1 December 1860 to August 1861.[1] In October 1861, Chapman and Hall published the novel in three volumes.[2][3][4]\n" +
                    "\n" +
                    "The novel is set in Kent and London in the early to mid-19th century[5] and contains some of Dickens's most celebrated scenes, starting in a graveyard, where the young Pip is accosted by the escaped convict Abel Magwitch.[6] Great Expectations is full of extreme imagery – poverty, prison ships and chains, and fights to the death[6] – and has a colourful cast of characters who have entered popular culture. These include the eccentric Miss Havisham, the beautiful but cold Estella, and Joe, the unsophisticated and kind blacksmith. Dickens's themes include wealth and poverty, love and rejection, and the eventual triumph of good over evil.[6] Great Expectations, which is popular both with readers and literary critics,[7][8] has been translated into many languages and adapted numerous times into various media.\n" +
                    "\n" +
                    "Upon its release, the novel received near universal acclaim.[7] Although Dickens's contemporary Thomas Carlyle referred to it disparagingly as that \"Pip nonsense,\" he nevertheless reacted to each fresh installment with \"roars of laughter.\"[9] Later, George Bernard Shaw praised the novel, as \"All of one piece and consistently truthful.\"[10] During the serial publication, Dickens was pleased with public response to Great Expectations and its sales;[11] when the plot first formed in his mind, he called it \"a very fine, new and grotesque idea.\"[12]\n" +
                    "\n" +
                    "In the 21st century, the novel retains good ratings among literary critics[13] and in 2003 it was ranked 17th on the BBC’s The Big Read poll.[14]"
            },
            {
                image: "https://lh3.googleusercontent.com/proxy/o2nz0UtsK4hMrffHOLOl8Nbjs95DFcx5F2YpRJcbwCoNz1XscyhtCLWvUGnOalHa9ks8Nh5pQ5r-KxE5wS11OmhhQTlyUbJfRBGdCg6tiPSS8hKp",
                title: "David Copperfield",
                description: "David Copperfield is the eighth novel by Charles Dickens. The novel's full title is The Personal History, Adventures, Experience and Observation of David Copperfield the Younger of Blunderstone Rookery (Which He Never Meant to Publish on Any Account).[N 1] It was first published as a serial in 1849–50, and as a book in 1850.\n" +
                    "\n" +
                    "The novel features the character David Copperfield, and is written in the first person, as a description of his life until middle age, with his own adventures and the numerous friends and enemies he meets along his way. It is his journey of change and growth from infancy to maturity, as people enter and leave his life and he passes through the stages of his development.\n" +
                    "\n" +
                    "It is often described as his masterpiece, \"the triumph of the art of Dickens\",[2][3] which marks a turning point in his work, the point of separation between the novels of youth and those of maturity.[3][4] Though written in the first person, David Copperfield is considered to be more than an autobiography, going beyond this framework in the richness of its themes and the originality of its writing, which makes it a true autobiographical novel.[4][5] In the words of the author, this novel was \"a very complicated weaving of truth and invention\".[6] Some elements of the novel follow events in Dickens's own life.[7] It was Dickens' favourite among his own novels. In the preface to the 1867 edition, Dickens wrote, \"like many fond parents, I have in my heart of hearts a favourite child. And his name is David Copperfield.\"[8]\n" +
                    "\n" +
                    "Dickens wrote this novel without an outline, unlike the way he wrote Dombey and Son, the previous novel. He wrote chapter summaries after the chapters were completed. Some aspects of the story were fixed in his mind from the start, but others, like the obsession of Mr Dick with Charles I, the profession of David Copperfield as a writer, and the sad fate of Dora, were not decided by Dickens until the serial publications were underway; August 1849, December 1849 and May 1850, respectively, were the dates when those decisions were made.[9]\n" +
                    "\n" +
                    "At first glance, the work is modeled in the loose and somewhat disjointed way of \"personal histories\" that was very popular in the United Kingdom of the 18th century;[N 2] but in reality, David Copperfield is a carefully structured and unified novel. It begins, like other novels by Dickens, with a rather bleak painting of the conditions of childhood in Victorian England, notoriously when the troublesome children are parked in infamous boarding schools, then he strives to trace the slow social and intimate ascent of a young man who, painfully providing for the needs of his good aunt while continuing his studies, ends up becoming a writer; the story, writes Paul Davis, of \"a Victorian everyman seeking self-understanding\".[4]\n" +
                    "\n" +
                    "The novel has a primary theme of growth and the changes that occur on the way to maturity. In addition, Dickens included many aspects of Victorian Era life that he wanted to highlight or wished to change, which were primarily integrated into the story, using satire as one device. The plight of prostitutes and the attitude of middle class society to them, the status of women in marriage, the rigid class structure, are aspects that he highlighted, while the system for handling criminals, the quality of schools, and the employment of children in the fast-spreading factories of the 19th century were aspects he wished to influence, to change for the better. He, among other authors, achieved success in bringing about changes regarding child labour and schooling for more children up to age 12.[10]"
            },
        ],
    },
]
export default data;
